{% set name = "pyjuliacall" %}
{% set pypi_name = "juliacall" %}
{% set version = "0.9.27" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/juliacall-{{ version }}.tar.gz
  sha256: 94c3ef2fe2597417ef79a705e60a1c312294a7863d55515536896bb4fb3faf3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pyjuliapkg >=0.1.17,<0.2.dev0

test:
  imports:
    - juliacall
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/JuliaPy/PythonCall.jl
  summary: Julia and Python in seamless harmony
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilesCranmer
    - mkitti
