{% set name = "pyjuliacall" %}
{% set pypi_name = "juliacall" %}
{% set version = "0.9.24" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/juliacall-{{ version }}.tar.gz
  sha256: 31bed223489b535e4e8db46bfff4596350c24f757b9c2d17296c07397f75948b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=42
    - wheel
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pyjuliapkg >=0.1.8,<0.2.dev0

test:
  imports:
    - juliacall
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/JuliaPy/PythonCall.jl
  summary: Julia and Python in seamless harmony
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilesCranmer
    - mkitti
